const READY = 'READY?';
const WORKING = 'WORKING';
const BREAK = 'BREAK';
const AUTO_START_AFTER_BREAK = 'AUTO_START_AFTER_BREAK';
const MANUAL_START_AFTER_BREAK = 'MANUAL_START_AFTER_BREAK';

export {
  READY,
  WORKING,
  BREAK,
  AUTO_START_AFTER_BREAK,
  MANUAL_START_AFTER_BREAK,
};
